language: node_js
node_js:
- '8'
cache:
  directories:
  - "$HOME/gcloud/"
env:
- PATH=$PATH:$HOME/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_4d75f9e9b759_key -iv $encrypted_4d75f9e9b759_iv
  -in gce-key.json.enc -out gce-key.json -d
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- if [ ! -d $HOME/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file gce-key.json
- echo "  SCS_API:" $SCS_API >> app.yaml
- npm install
- npm run build:prod
install:
- gcloud config set compute/zone us-east1-b
- gcloud config set project scs-shadow
script:
- gcloud -q app deploy app.yaml
