before_install:
- openssl aes-256-cbc -K $encrypted_4d75f9e9b759_key -iv $encrypted_4d75f9e9b759_iv
  -in scs-shadow-e5e41dfcb0f6.json.enc -out scs-shadow-e5e41dfcb0f6.json -d
deploy:
  provider: gae
  keyfile: scs-shadow-e5e41dfcb0f6.json
  project: default
