service: stage-scs-app
runtime: nodejs
env: flex
resources:
  cpu: 1
  memory_gb: 1.6
  disk_size_gb: 10
skip_files:
  - ^(.*/)?.*/node_modules/.*$
health_check:
  enable_health_check: False
env_variables:
  NODE_ENV: production
